name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.11'

      - name: Download FFmpeg
        run: |
          curl -L -o ffmpeg.zip https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
          tar -xf ffmpeg.zip
          for /d %%i in (ffmpeg-*) do set FFMPEG_DIR=%%i
          copy %FFMPEG_DIR%\bin\ffmpeg.exe .
          copy %FFMPEG_DIR%\bin\ffprobe.exe .
        shell: cmd

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --add-binary="ffmpeg.exe:." --add-binary="ffprobe.exe:." extract_audio.py
            
      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        with:
          files: dist/extract_audio.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
